[lldb] Run monorepo_build.py under Python 3

diff --git a/zorg/jenkins/jobs/jobs/lldb-cmake b/zorg/jenkins/jobs/jobs/lldb-cmake
--- a/zorg/jenkins/jobs/jobs/lldb-cmake
+++ b/zorg/jenkins/jobs/jobs/lldb-cmake
@@ -39,7 +39,7 @@ pipeline {
         steps {
             timeout(10) {
                     sh '''
-                    python llvm-zorg/zorg/jenkins/monorepo_build.py fetch
+                    python3 llvm-zorg/zorg/jenkins/monorepo_build.py fetch
                     '''
                 }
             }
@@ -65,12 +65,12 @@ pipeline {
 
                     if test -f /opt/codesign-workaround.sh; then sh /opt/codesign-workaround.sh init lldb-build/bin/debugserver; fi
                     export MAX_PARALLEL_TESTS=$(sysctl hw.physicalcpu |awk '{print $2}')
-                    python llvm-zorg/zorg/jenkins/monorepo_build.py lldb-cmake build \
+                    python3 llvm-zorg/zorg/jenkins/monorepo_build.py lldb-cmake build \
                       --assertions \
                       --projects="clang;lld;lldb;cross-project-tests"  \
                       --runtimes="libcxx;libcxxabi;compiler-rt"  \
                       --compiler-flag="-Wdocumentation" \
-                      --cmake-type=Release || (echo "Retrying. debuginfo-tests may have failed due to high load."; sleep 30; python llvm-zorg/zorg/jenkins/monorepo_build.py lldb-cmake build \
+                      --cmake-type=Release || (echo "Retrying. debuginfo-tests may have failed due to high load."; sleep 30; python3 llvm-zorg/zorg/jenkins/monorepo_build.py lldb-cmake build \
                       --assertions \
                       --projects="clang;lld;lldb;cross-project-tests"  \
                       --runtimes="libcxx;libcxxabi;compiler-rt"  \
@@ -107,7 +107,7 @@ pipeline {
 
                         export MAX_PARALLEL_TESTS=$(sysctl hw.physicalcpu |awk '{print $2}')
 
-                        python llvm-zorg/zorg/jenkins/monorepo_build.py lldb-cmake-debuginfo test
+                        python3 llvm-zorg/zorg/jenkins/monorepo_build.py lldb-cmake-debuginfo test
                         '''
                     }
                 }
@@ -121,7 +121,7 @@ pipeline {
                     export PATH=$PATH:/usr/bin:/usr/local/bin
 
                     export MAX_PARALLEL_TESTS=$(sysctl hw.physicalcpu |awk '{print $2}')
-                    python llvm-zorg/zorg/jenkins/monorepo_build.py lldb-cmake test
+                    python3 llvm-zorg/zorg/jenkins/monorepo_build.py lldb-cmake test
                     '''
                 }
             }
@@ -140,7 +140,7 @@ pipeline {
                     export GIT_SHA=${sha:1}
 
                     cd -
-                    python llvm-zorg/zorg/jenkins/monorepo_build.py properties
+                    python3 llvm-zorg/zorg/jenkins/monorepo_build.py properties
                     '''
              }
           }
